import { nanoid } from "nanoid";
import {
  FaAccessibleIcon,
  FaAtlassian,
  FaChartBar,
  FaCode,
  FaDev,
  FaFigma,
  FaGit,
  FaGithub,
  FaHtml5,
  FaJs,
  FaPhp,
  FaReact,
  FaRProject,
  FaToolbox,
} from "react-icons/fa";
import { FaDiagramNext, FaDiagramProject } from "react-icons/fa6";
import { SiFigma } from "react-icons/si";

export const links = [
  { id: nanoid(), href: "#home", text: "home" },
  { id: nanoid(), href: "#skills", text: "skills" },
  { id: nanoid(), href: "#about", text: "about" },
  { id: nanoid(), href: "#projects", text: "projects" },
];

export const skills = [
  {
    id: nanoid(),
    title: "Gestion de projets & Méthodologies",
    icon: <FaDiagramProject className="h-16 w-16 text-emerald-500" />,
    text: "Méthodologie Agile Scrum : pilotage de projets web complexes avec planification des sprints, suivi des user stories, rituels agiles (daily, sprint review, rétrospectives).",
  },
  {
    id: nanoid(),
    title: "HTML&CSS",
    icon: <FaHtml5 className="h-16 w-16 text-emerald-500" />,
    text: "Compétences en HTML et CSS, capable de créer des sites web visuellement attractifs et responsives pour offrir une expérience utilisateur optimale. Bonnes pratiques Opquast, accessibilité. ",
  },
  {
    id: nanoid(),
    title: "Javascript",
    icon: <FaJs className="h-16 w-16 text-emerald-500" />,
    text: "Compétences en JavaScript, pour la création d'applications web interactives et dynamiques, en mettant l'accent sur des interactions utilisateur fluides et une fonctionnalité optimale. Manipulation du DOM, appels asynchrones (Fetch, Promises, async/await), gestion des événements, programmation fonctionnelle et orientée objet.",
  },
  {
    id: nanoid(),
    title: "React",
    icon: <FaReact className="h-16 w-16 text-emerald-500" />,
    text: "Compétences en React, pour le développement d'applications front-end efficaces et interactives, intégration d’APIs, gestion de formulaires, filtres, modales, listes dynamiques et dashboards. Approche modulaire et maintenable, avec optimisation des performances et accessibilité.",
  },
  {
    id: nanoid(),
    title: "UX/UI Design",
    icon: <FaFigma className="h-16 w-16 text-emerald-500" />,
    text: "Design d’interfaces : création de maquettes, design systems, prototypage interactif, tests utilisateurs, audit UX, tests modérés/non modérés, analyse heuristique, amélioration continue.",
    tools: "Outils : Figma, Adobe XD",
  },
  {
    id: nanoid(),
    title: "Jira",
    icon: <FaAtlassian className="h-16 w-16 text-emerald-500" />,
    text: "Compétences sur l’outil de gestion de projet agile pour planifier, suivre et coordonner efficacement les tâches en équipe. Configuration de workflows, gestion des sprints Scrum/Kanban, suivi des tickets, et reporting pour une meilleure visibilité sur l'avancement des projets. Collaboration avec les équipes pluridisciplinaires (PO,QA).",
  },
  // {
  //   id: nanoid(),
  //   title: "",
  //   icon: <FaChartBar className="h-16 w-16 text-emerald-500" />,
  //   text: "",
  // },
  {
    id: nanoid(),
    title: "ToolBox",
    icon: <FaToolbox className="h-16 w-16 text-emerald-500" />,
    text: "Utilisation d’outils collaboratifs (Jira, Trello, Confluence, Miro, Azure DevOps) pour la planification, le suivi de backlog et la priorisation.",
  },
  {
    id: nanoid(),
    title: "Git/GitHub",
    icon: <FaGithub className="h-16 w-16 text-emerald-500" />,
    text: "Utilisation quotidienne de pour le versioning, la gestion de branches, les merges, résolution de conflits, pull requests, revue de code,documentation collaborative.",
  },
  {
    id: nanoid(),
    title: "Php",
    icon: <FaPhp className="h-16 w-16 text-emerald-500" />,
    text: "Copetences back-end orienté objet (POO), gestion des requêtes SQL (MySQL), intégration d'APIs REST, génération de PDF, traitement de formulaires.",
  },
  // {
  //   id: nanoid(),
  //   title: "",
  //   icon: <FaCode className="h-16 w-16 text-emerald-500" />,
  //   text: "",
  // },
];

export const projects = [
  {
    id: nanoid(),
    img: "../src/assets/imgstarwars-min.jpg",
    url: "https://cfy1010.github.io/CyIntroStarWars/",
    github: "https://github.com/Cfy1010/CyIntroStarWars",
    title: "Star Wars opening crawl",
    text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.",
  },
  {
    id: nanoid(),
    img: "../src/assets/cysound-min.jpg",
    url: "https://cfy1010.github.io/CySounds/",
    github: "https://github.com/Cfy1010/CySounds",
    title: "CySounds",
    text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.",
  },
  {
    id: nanoid(),
    img: "../src/assets/cynews-min.jpg",
    url: "https://cfy1010.github.io/Cy-News/",
    github: "https://github.com/Cfy1010/Cy-News",
    title: "CyNews",
    text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
  },
  {
    id: nanoid(),
    img: "../src/assets/guitargods-min.jpg",
    url: "https://cfy1010.github.io/CyGuitarGods/",
    github: "https://github.com/Cfy1010/CyGuitarGods",
    title: "Guitar Gods",
    text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.",
  },
  {
    id: nanoid(),
    img: "../src/assets/zazymusic-min.jpg",
    url: "https://cfy1010.github.io/CyMusicPlayer/",
    github: "https://github.com/Cfy1010/CyMusicPlayer",
    title: "Zazy's Music Player",
    text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.",
  },
  {
    id: nanoid(),
    img: "../src/assets/modernportfolio.png",
    url: "https://cfy1010.github.io/CyModernPortfolio/",
    github: "https://github.com/Cfy1010/CyModernPortfolio",
    title: "CyModernPortfolio",
    text: "1er portfolio datant de 2019",
  },
  {
    id: nanoid(),
    img: "../src/assets/formvalidator-min.png",
    url: "https://cfy1010.github.io/CyFormValidator/",
    github: "https://github.com/Cfy1010/CyFormValidator",
    title: "Little Form Validator in HTML5 CSS3 & JS",
    text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.",
  },
  {
    id: nanoid(),
    img: "../src/assets/cyaccessform.png",
    url: "https://cfy1010.github.io/CyAccessForm/",
    github: "https://github.com/Cfy1010/CyAccessForm",
    title: "CyAccessForm",
    text: "Exemples d'accessibilité en HTML.",
  },
  {
    id: nanoid(),
    img: "../src/assets/todolist_in_react.png",
    url: "https://cfy1010.github.io/todolist-in-react/",
    github: "https://github.com/Cfy1010/todolist-in-react",
    title: "todolist_in_react",
    text: "",
  },
  {
    id: nanoid(),
    img: "../src/assets/todolist-vanillajs-min.png",
    url: "https://cfy1010.github.io/todolist/",
    github: "https://github.com/Cfy1010/todolist",
    title: "My TodoList",
    text: "Petite TodoListe en Vanilla JS.",
  },
  {
    id: nanoid(),
    img: "../src/assets/todos-min.jpg",
    // url: "https://cfy1010.github.io/todolist/",
    github: "https://github.com/Cfy1010/CyToDoList",
    title: "CyToDoList",
    text: "Autre petite todoListe en Vanilla JS.",
  },
  {
    id: nanoid(),
    img: "../src/assets/cysong-min.jpg",
    url: "https://cfy1010.github.io/CyLyricsSearchApp/",
    github: "https://github.com/Cfy1010/CyLyricsSearchApp",
    title: "Lyrics Search App",
    text: "Web App de recherche de lyrics.",
  },
  {
    id: nanoid(),
    img: "../src/assets/respire-min.jpg",
    url: "https://cfy1010.github.io/CyRelaxerApp/",
    github: "https://github.com/Cfy1010/CyRelaxerApp",
    title: "Relaxer App",
    text: "Petite Web App pour se relaxer.",
  },
  {
    id: nanoid(),
    img: "../src/assets/cyimmo-min.jpg",
    url: "https://cfy1010.github.io/CyPyImmo/",
    github: "https://github.com/Cfy1010/CyPyImmo",
    title: "CyPyImmo",
    text: "Python + Django + PostgreSQL (à partir d'un site statique HTML/CSS/Bootstrap/Lightbox).",
  },
  {
    id: nanoid(),
    img: "../src/assets/cymovies-min.jpg",
    url: "https://cfy1010.github.io/CyMovies-2022/",
    github: "https://github.com/Cfy1010/CyMovies-2022",
    title: "CyMovies",
    text: "Mes coups de coeurs cinema !.",
  },
];
